### ISSUE TITLE
linux chromium 54

### ISSUE THREAD

**Issue by posix4e** [brave/electron#94]
- [x]  Hack and Slash to get it to compile
- [x] Move gtk and dbus dependency out of chrome (Some technical debt i created) 
- [x] Identify what native window work to do.
- [x] Hack & slash to link
### Ok It's starting remaining issues 
- [x] Webpack-dev-server, web-notifier not found errors
- [x] Error: Cannot find module 'immutable', normalize-url, electron-localshortcut, immutablediff, l20n, Intl
### Ok I can hit google Now for the cleanup
- [x] Fix create_dist for linux
- [x]  Repair brave to know how to LD in libnode
- [x] Inherit local variables in start.js
### Validation
- [x] Verify our application directory is correct
- [x] Verify gpu behavior
- [x] Complete rsync to browser-laptop
### Bonus points
- [x] Verify deb and rpm package builds
- [x] Verify publish nightly apt repo

**Comment by bbondy** [comment]
Re-enable widevine doesn't need to block for 54 upgrade since it's intentionally disabled on Linux.  The component updater that we use on mac and Windows doesn't have binaries for Linux, so that needs to be added with the alt method of HTTP download location which we haven't done yet.  So basically I'd remove that checkbox for this 54 tracking task.
